spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gdelt?useSSL=false&useTimezone=true&serverTimezone=America/New_York&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&transformedBitIsBoolean=true
    username: gdelt
    password: gdelt
    test-while-idle: true
    validation-query: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      initial-size: 10
      jdbc-interceptors: org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer
      jmx-enabled: true
      log-abandoned: true
      max-active: 100
      max-wait: 10000
      min-evictable-idle-time-millis: 30000
      min-idle: 10
      remove-abandoned: true
      remove-abandoned-timeout: 60
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      time-between-eviction-runs-millis: 30000
      validation-interval: 30000
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        hbm2ddl:
          import_files: db-seed.sql